const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
import fs from 'node:fs';import assert from 'node:assert/strict';
const pg=new PGlite();
await pg.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create table auth.users(id uuid primary key);
create function auth.uid()returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create type public.payment_status as enum('unpaid','partially_paid','paid','refunded');
create type public.order_record_status as enum('active','voided');
create table public.user_profiles(id uuid primary key references auth.users(id),role text,is_active boolean);
create table public.orders(id uuid primary key default gen_random_uuid(),payment_provider text,payment_method text,payment_status public.payment_status default 'unpaid',amount_paid numeric default 0,record_status public.order_record_status default 'active',processing_cost numeric default 0,shipping_amount numeric default 0,fulfillment_method text,shipping_rate_id uuid,shipping_bag_count integer,shipping_rate_source text,shipping_carrier text,shipping_rate_retail numeric,shipping_rate_list numeric,shipping_rate_account numeric,shipping_package_weight_ounces numeric,shipping_rate_label text,shipping_service text,shipping_postage_amount numeric,shipping_packaging_charge numeric,shipping_easypost_rate_id text,shipping_easypost_shipment_id text,shipping_rate_environment text,payment_session_id text,payment_transaction_id text,refunded_amount numeric,refund_transaction_id text,refunded_at timestamptz,void_reason text,voided_at timestamptz,voided_by uuid);
create table public.order_items(order_id uuid references public.orders(id),line_total numeric);
create table public.scouts(id uuid primary key,is_active boolean,is_general_fund boolean);
create table public.scout_credit_transactions(id uuid primary key default gen_random_uuid(),scout_id uuid references public.scouts(id),transaction_type text,amount numeric,transaction_date date,purpose text,reference_number text,notes text,created_by uuid,updated_by uuid);
create view public.scout_summary as select s.id scout_id,coalesce(sum(case when t.transaction_type='transfer_to_pack' then -t.amount else t.amount end),0)available_credit from public.scouts s left join public.scout_credit_transactions t on t.scout_id=s.id group by s.id;
create function public.create_storefront_order(jsonb,jsonb,numeric)returns jsonb language plpgsql as $$declare oid uuid;begin insert into public.orders(processing_cost)values($3)returning id into oid;insert into public.order_items(order_id,line_total)values(oid,12);return jsonb_build_object('order_id',oid,'store_order_number','TEST-1');end$$;
insert into auth.users values('00000000-0000-0000-0000-000000000001');
insert into public.user_profiles values('00000000-0000-0000-0000-000000000001','coffee_bean',true);
insert into public.scouts values('00000000-0000-0000-0000-000000000002',true,false);
insert into public.scout_credit_transactions(scout_id,transaction_type,amount)values('00000000-0000-0000-0000-000000000002','opening_balance',100);`);
const sql=fs.readFileSync(new URL('../supabase/paypal_setup.sql',import.meta.url),'utf8');
await pg.exec(sql);await pg.exec(sql);console.log('SQL installed and replayed successfully.');
const payload={customer:{},items:[],processing_cost:0,fulfillment:{fulfillment_method:'pickup',shipping_amount:0}};
const create=async(env)=> (await pg.query(`insert into public.paypal_checkouts(environment,request_key,fingerprint,amount,payload,paypal_order_id) values($1,gen_random_uuid(),'test',12,$2,$3)returning *`,[env,JSON.stringify(payload),'ORDER-'+env])).rows[0];
const sandbox=await create('sandbox');
let done=(await pg.query(`select public.complete_paypal_checkout($1,$2,$3,12,'USD',0.91)c`,[sandbox.id,'ORDER-sandbox','CAPTURE-sandbox'])).rows[0].c;
assert.equal(done.status,'completed');assert.equal((await pg.query('select count(*)::int n from public.orders')).rows[0].n,0);
await pg.query(`select public.complete_paypal_checkout($1,$2,$3,12,'USD',0.91)`,[sandbox.id,'ORDER-sandbox','CAPTURE-sandbox']);
await assert.rejects(pg.query(`select public.complete_paypal_checkout($1,$2,'other',11,'USD',0.91)`,[sandbox.id,'ORDER-sandbox']),/does not match/);
const live=await create('live');await pg.query('select public.prepare_paypal_live_order($1)',[live.id]);
await pg.query(`select public.complete_paypal_checkout($1,'ORDER-live','CAPTURE-live',12,'USD',0.91)`,[live.id]);
assert.equal((await pg.query('select payment_status from public.orders')).rows[0].payment_status,'paid');
await pg.query(`select public.record_paypal_refund($1,'REFUND1',5,'USD','test',null)`,[live.id]);
assert.equal(Number((await pg.query('select amount_paid from public.orders')).rows[0].amount_paid),7);
await pg.query(`select public.record_paypal_refund($1,'REFUND1',5,'USD','retry',null)`,[live.id]);
await assert.rejects(pg.query(`select public.record_paypal_refund($1,'TOO-MUCH',8,'USD','test',null)`,[live.id]),/exceeds/);
await pg.query(`select public.record_paypal_refund($1,'REFUND2',7,'USD','test',null)`,[live.id]);
assert.equal((await pg.query('select record_status from public.orders')).rows[0].record_status,'voided');
const lines=JSON.stringify([{scout_id:'00000000-0000-0000-0000-000000000002',amount:40}]);
const args=['00000000-0000-0000-0000-000000000003','00000000-0000-0000-0000-000000000001','paypal','REF123','Camp','2026-09-30',lines];
await pg.query('select public.record_paypal_pack_transfer($1,$2,$3,$4,$5,$6,$7)',args);
await pg.query('select public.record_paypal_pack_transfer($1,$2,$3,$4,$5,$6,$7)',args);
assert.equal(Number((await pg.query('select available_credit from public.scout_summary')).rows[0].available_credit),60);
await assert.rejects(pg.query('select public.record_paypal_pack_transfer($1,$2,$3,$4,$5,$6,$7)',['00000000-0000-0000-0000-000000000004',...args.slice(1,3),'REF124',...args.slice(4,6),JSON.stringify([{scout_id:'00000000-0000-0000-0000-000000000002',amount:61}])]),/exceeds/);
assert.equal((await pg.query(`select has_function_privilege('anon','public.complete_paypal_checkout(uuid,text,text,numeric,text,numeric)','execute') allowed`)).rows[0].allowed,false);
assert.equal((await pg.query(`select has_function_privilege('authenticated','public.record_paypal_pack_transfer(uuid,uuid,text,text,text,date,jsonb)','execute')allowed`)).rows[0].allowed,false);
console.log('Verified sandbox isolation, live linkage, amount validation, duplicate capture/refund/transfer handling, over-refund/over-credit rejection, and privileged-function grants.');
await pg.close();
