import {requirePortalUser} from '../../assets/auth-common.js';
import {renderPortalLayout,escapeHtml} from '../components/layout.js';
import {DataGrid} from '../components/data-grid.js';
import {FundraisingService} from '../services/fundraising-service.js';
import {hasMinimumRole} from '../shared/roles.js';
import {money,setNotice,openDialog,closeDialog,clearNotice,setFormBusy} from '../master-data/shared.js';
import {confirmAction} from '../components/confirm-dialog.js';
const result=await requirePortalUser();if(result)await initialize(result);
async function initialize({user,profile}){
 const manage=hasMinimumRole(profile.role,'coffee_bean'),content=renderPortalLayout({user,profile,pageTitle:'Transfers'});
 content.innerHTML=`<div class="breadcrumb">Committee Portal / Transfers</div><div class="page-heading"><div><h1>Scout Credit Transfers</h1><p>Transfer funds to Pack checking in PayPal, then record the completed transfer and apply Scout credits here.</p></div><div>${manage?'<button class="portal-button" id="record-transfer">Record Completed Transfer</button><button class="portal-button portal-button--secondary" id="adjust">Record Adjustment</button>':''}</div></div><div class="notice" id="notice" hidden></div><section class="panel"><h2>Completed Transfers</h2><p>This ledger records transfers you already completed. It does not initiate a bank withdrawal.</p><div id="new-history"></div></section><section class="panel"><h2>Historical Payouts</h2><div id="legacy-history"></div></section><section class="panel"><h2>Credit Transactions</h2><div id="credit-history"></div></section>${manage?dialogs():''}`;
 const notice=document.querySelector('#notice');let summary=[],scouts=[];
 const transfers=new DataGrid({container:'#new-history',columns:[{key:'transfer_date',label:'Date'},{key:'source',label:'Source'},{key:'reference',label:'Reference'},{key:'purpose',label:'Purpose'},{key:'amount',label:'Scout Credits',render:r=>money(r.amount)},{key:'report',label:'Report',render:r=>`<a href="/committee/payout-report.html?kind=paypal&id=${encodeURIComponent(r.id)}">View Report</a>`}],searchFields:['reference','purpose','source'],exportFileName:'pack-transfers.csv'});
 const history=new DataGrid({container:'#legacy-history',columns:[{key:'payout_number',label:'Transfer'},{key:'purpose',label:'Purpose'},{key:'total_amount',label:'Amount',render:r=>money(r.total_amount)},{key:'status',label:'Status'},{key:'report',label:'Report',render:r=>`<a href="/committee/payout-report.html?id=${encodeURIComponent(r.id)}">View Historical Report</a>`}],searchFields:['payout_number','purpose'],exportFileName:'historical-payouts.csv'});
 const credits=new DataGrid({container:'#credit-history',columns:[{key:'transaction_date',label:'Date'},{key:'scout',label:'Scout',render:r=>escapeHtml(name(r.scouts))},{key:'transaction_type',label:'Type'},{key:'amount',label:'Amount',render:r=>money(r.amount)},{key:'purpose',label:'Purpose'},{key:'reference_number',label:'Reference'}],searchFields:['purpose','reference_number'],exportFileName:'scout-credit-transactions.csv'});
 async function load(){try{const [s,sc,t,p,tx]=await Promise.all([FundraisingService.summary(),FundraisingService.scouts(),FundraisingService.paypalTransfers(),FundraisingService.payouts(),FundraisingService.transactions()]);summary=s;scouts=sc;transfers.setRows(t);history.setRows(p);credits.setRows(tx);}catch(e){setNotice(notice,e.message,'error');}}
 await load();if(!manage)return;
 const dialog=document.querySelector('#transfer-dialog'),form=dialog.querySelector('form'),list=document.querySelector('#scout-lines'),fn=document.querySelector('#transfer-notice');let requestKey;
 document.querySelector('#record-transfer').onclick=()=>{form.reset();requestKey=crypto.randomUUID();form.elements.transfer_date.value=new Date().toLocaleDateString('en-CA');clearNotice(fn);list.innerHTML=summary.filter(s=>!s.is_general_fund&&Number(s.available_credit)>0).map(s=>`<label class="form-field"><span>${escapeHtml([s.first_name,s.last_name].join(' '))} — available ${money(s.available_credit)}</span><input type="number" min="0" step="0.01" max="${Number(s.available_credit).toFixed(2)}" value="0.00" data-scout="${escapeHtml(s.scout_id)}"></label>`).join('')||'<p>No available Scout credit.</p>';openDialog(dialog);};
 dialog.querySelector('[data-close]').onclick=()=>closeDialog(dialog);
 form.onsubmit=async event=>{event.preventDefault();clearNotice(fn);const fd=new FormData(form),lines=[...list.querySelectorAll('input')].map(x=>({scout_id:x.dataset.scout,amount:Number(x.value)})).filter(x=>x.amount>0);if(!lines.length)return setNotice(fn,'Enter at least one Scout amount.','error');const amount=lines.reduce((s,l)=>s+l.amount,0);if(!await confirmAction({title:'Record Completed Transfer?',message:`Apply ${money(amount)} in Scout credit against transfer ${fd.get('reference')}? Confirm these funds already reached Pack checking.`,confirmLabel:'Record Transfer'}))return;setFormBusy(form,true);try{const recorded=await FundraisingService.recordPaypalTransfer({request_key:requestKey,source:fd.get('source'),reference:fd.get('reference'),purpose:fd.get('purpose'),transfer_date:fd.get('transfer_date'),lines});closeDialog(dialog);const failed=recorded.parent_notifications?.filter(n=>n.status==='failed').length||0;setNotice(notice,'Completed transfer recorded and Scout credits applied.'+(failed?' Some parent emails need attention.':''),failed?'error':'success');await load();}catch(e){setNotice(fn,e.message,'error');}finally{setFormBusy(form,false);}};
 const ad=document.querySelector('#adjust-dialog'),af=ad.querySelector('form');document.querySelector('#adjust').onclick=()=>{af.reset();af.elements.scout_id.innerHTML=scouts.filter(s=>s.is_active).map(s=>`<option value="${escapeHtml(s.id)}">${escapeHtml(name(s))}</option>`).join('');af.elements.transaction_date.value=new Date().toLocaleDateString('en-CA');openDialog(ad);};ad.querySelector('[data-close]').onclick=()=>closeDialog(ad);
 af.onsubmit=async event=>{event.preventDefault();setFormBusy(af,true);const fd=new FormData(af);try{await FundraisingService.createTransaction({scout_id:fd.get('scout_id'),transaction_type:fd.get('transaction_type'),amount:Number(fd.get('amount')),transaction_date:fd.get('transaction_date'),purpose:fd.get('purpose'),created_by:user.id,updated_by:user.id});closeDialog(ad);await load();}catch(e){setNotice(document.querySelector('#adjust-notice'),e.message,'error');}finally{setFormBusy(af,false);}};
}
function name(s){return s?.is_general_fund?'General Fund':[s?.first_name,s?.last_name].filter(Boolean).join(' ');}
function dialogs(){return `<dialog class="portal-dialog portal-dialog--wide" id="transfer-dialog"><form class="dialog-card"><h2>Record Completed Transfer</h2><p>Enter the completed transfer reference from PayPal or your bank. This applies credits and records the transfer; it does not send money.</p><label class="form-field"><span>Source</span><select name="source"><option value="paypal">PayPal to Pack checking</option><option value="bank">Funds already in Pack checking</option></select></label><label class="form-field"><span>Completed transfer reference</span><input name="reference" required maxlength="180"></label><label class="form-field"><span>Purpose</span><input name="purpose" required maxlength="500"></label><label class="form-field"><span>Transfer date</span><input name="transfer_date" type="date" required></label><div id="scout-lines" class="form-grid"></div><div id="transfer-notice" class="notice" hidden></div><div class="dialog-actions"><button type="button" data-close class="portal-button portal-button--secondary">Cancel</button><button class="portal-button" type="submit">Record & Apply Credits</button></div></form></dialog><dialog class="portal-dialog" id="adjust-dialog"><form class="dialog-card"><h2>Record Adjustment</h2><label class="form-field"><span>Scout</span><select name="scout_id" required></select></label><label class="form-field"><span>Type</span><select name="transaction_type"><option value="opening_balance">Opening Balance</option><option value="adjustment_credit">Credit Adjustment</option><option value="adjustment_debit">Debit Adjustment</option></select></label><label class="form-field"><span>Amount</span><input type="number" name="amount" min="0.01" step="0.01" required></label><label class="form-field"><span>Date</span><input type="date" name="transaction_date" required></label><label class="form-field"><span>Purpose</span><input name="purpose" required></label><div id="adjust-notice" class="notice" hidden></div><div class="dialog-actions"><button type="button" data-close class="portal-button portal-button--secondary">Cancel</button><button class="portal-button" type="submit">Record Adjustment</button></div></form></dialog>`;}
